# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('isreproduce', models.BooleanField(verbose_name='\u662f\u5426\u8f6c\u8f7d')),
                ('publishtime', models.DateTimeField(auto_now=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('readtimes', models.IntegerField(verbose_name='\u9605\u8bfb\u91cf')),
                ('auther', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publishtime'],
            },
        ),
        migrations.CreateModel(
            name='blogtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=30, verbose_name='\u7c7b\u578b\u540d\u79f0')),
                ('count', models.IntegerField(verbose_name='\u4f5c\u54c1\u6570\u91cf')),
                ('tips', models.IntegerField(verbose_name='\u7c7b\u578b\u8bbf\u95ee\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='\u90ae\u7bb1')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('replaytime', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='red.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=30, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('tagcount', models.IntegerField(verbose_name='\u6807\u7b7e\u4f5c\u54c1\u6570\u91cf')),
                ('tagcreatedata', models.DateTimeField(auto_now_add=True, verbose_name='\u6807\u7b7e\u521b\u5efa\u65f6\u95f4')),
                ('tagtips', models.IntegerField(verbose_name='\u6807\u7b7e\u8bbf\u95ee\u91cf')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='red.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='typefor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.blogtype'),
        ),
    ]
