# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0002_auto_20160906_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contry',
            new_name='country',
        ),
    ]
