# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0002_auto_20160919_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='heading',
            field=models.ImageField(blank=True, upload_to='user_img', verbose_name='\u5934\u50cf'),
        ),
    ]
