# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-19 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0003_auto_20160919_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='heading',
            field=models.ImageField(blank=True, upload_to='article_img', verbose_name='\u56fe\u7247'),
        ),
    ]
