# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-19 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0004_article_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='heading',
            new_name='workimg',
        ),
    ]
